name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish-docker-images:
    needs: publish-packages
    runs-on: ubuntu-latest
    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Docker meta for the backend
        id: metabackend
        uses: docker/metadata-action@v3
        with:
          images: codelit/courselit-backend

      - name: Docker meta for the frontend
        id: metafrontend
        uses: docker/metadata-action@v3
        with:
          images: codelit/courselit-frontend

      - name: Docker meta for the proxy
        id: metaproxy
        uses: docker/metadata-action@v3
        with:
          images: codelit/courselit-proxy

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/backend/Dockerfile
          push: true
          tags: ${{ steps.metabackend.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}

      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/frontend/Dockerfile
          push: true
          tags: ${{ steps.metafrontend.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_frontend.outputs.digest }}

      - name: Build and push proxy
        id: docker_build_proxy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/proxy/Dockerfile
          push: true
          tags: ${{ steps.metaproxy.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_proxy.outputs.digest }}